MvcWeb2/MvcWeb2/Areas/Admin/Controllers/SliderController.cs
using MvcWeb2.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWeb2.Areas.Admin.Controllers
{


    [Authorize(Roles ="yonetici")]
    
    public class SliderController : Controller
    {

        SakaryaSporEntities db = new SakaryaSporEntities();
        // GET: Admin/Slider
        public ActionResult Index()
        {

           var model = db.Slider.OrderBy(x=>x.ID).ToList();
            return View(model);
        }
        public ActionResult Add()
        {
            
            return View();
        }


        const string imageFolderPath = "/Content/sliderimages/";




        public ActionResult AddSlider(SliderModel model)
        {
            
            if(ModelState.IsValid)
            {

                string fileName = string.Empty;

                if (model.Resim !=null && model.Resim.ContentLength>0)
                {
                    fileName = model.Resim.FileName;
                    var path =Path.Combine(Server.MapPath("~"+imageFolderPath),fileName);
                    model.Resim.SaveAs(path);
                }

                
                Slider slider = new Slider();
                slider.BaslangicTarih = model.BaslangicTarih;
                slider.BitisTarih = model.BitisTarih;
                slider.SlideText = model.SlideText;
                slider.ResimYol = imageFolderPath+ fileName;

                db.Slider.Add(slider);
                db.SaveChanges();

            }
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            var model = db.Slider.Find(id);
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

            }
            else
            {
                return View(model);
            }
           
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }


        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }






    }
}

MvcWeb2/MvcWeb2/Areas/Admin/Views/Slider/Add.cshtml
@model MvcWeb2.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Yeni Slayt Ekleme</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">
  

        <div class="row">
            <div class="col-sm-12">
                  
                <div class="panel panel-primary">
                    <div class="panel-heading">
                       

                    </div>
                        @using(Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal" ,enctype = "multipart/form-data"  }))
                         {
                    <div class="panel-body">
                       
                        <br>
                    

                            <div class="form-group">
                                @Html.LabelFor(m => m.SlideText, new {@class ="col-sm-3 control-label" })

                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.SlideText, new {@class ="form-control",placeholder ="Slider Yazısı"})
                                  
                                </div>
                                <div class="col-sm-3">
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.BaslangicTarih, new { @class = "col-sm-3 control-label" })
                                
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.BaslangicTarih, new { @class = "form-control datepicker", placeholder = "BaslangicTarih" })
                                   
                                </div>
                                <div class="col-sm-3">
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.BitisTarih, new { @class = "col-sm-3 control-label" })

                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.BitisTarih, new { @class = "form-control datepicker" , placeholder = "BitisTarih" })

                                </div>
                                <div class="col-sm-3">
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Resim, new { @class = "col-sm-3 control-label" })

                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.Resim, new { @class = "form-control", placeholder = "ResimYol" ,type = "file" })

                                </div>
                                <div class="col-sm-3">
                                  
                                </div>
                            </div>


                     
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Submit</button>
                                    <button class="btn-default btn">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                        }
                </div>
            </div>
        </div>



   
    </div>
    @section plugincss{
        
        
        <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
        
        
        }
 
    @section jsplugins{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
    }

     @section scripts{
         
         <script type="text/javascript">
         $('.datepicker').datepicker({
             format: 'mm.dd.yyyy',
         });
     
          </script>
         
         
         }

MvcWeb2/MvcWeb2/Areas/Admin/Views/Slider/Delete.cshtml
@model MvcWeb2.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Silme</h2>


<div class="container">
    <div class="col-lg-12">

        <div id="1">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#4f8edc">
                    <h4>Silmek istediğinize emin misiniz?</h4>
                </div>
                <div class="panel-body">
                    <br />
                    <p><b>Silinecek slayt :</b>@Model.SlideText</p>  
                    <br />
                    <p> @Html.ActionLink("Kabul ediyorum", "DeleteConfirm", new { id = Model.ID }) | @Html.ActionLink("Kabul etmiyorum", "Index")</p>
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

MvcWeb2/MvcWeb2/Areas/Admin/Views/Slider/Edit.cshtml
@model MvcWeb2.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slayt Düzenleme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

       

        <div class="form-group">
            @Html.LabelFor(model => model.SlideText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SlideText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SlideText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BaslangicTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BitisTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcWeb2/MvcWeb2/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Tables</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Slayt Tablosu</h4>
                    <div class="options">

                    </div>
                </div>
                <div class="panel-body">
                 
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Baslangıç Tarih</th>
                                <th>Bitiş Tarih</th>
                                <th>Slide Text</th>
                                <th>Resim Yolu</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.SlideText</td>
                                    <td>@item.BaslangicTarih</td>
                                    <td>@item.BitisTarih</td>
                                    <td>@item.ResimYol</td>
                                    <td>@Html.ActionLink("Düzenle","Edit","Slider",new {id =item.ID },null)|@Html.ActionLink("Silme", "Delete", "Slider", new { id = item.ID }, null)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>