MvcWeb2/MvcWeb2/Areas/Admin/Controllers/RolYonetimController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MvcWeb2.Areas.Admin.Models;
using MvcWeb2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWeb2.Areas.Admin.Controllers
{
    [Authorize(Roles = "yonetici")]
    public class RolYonetimController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/RolYonetim
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(context);

            var roleManager = new RoleManager<IdentityRole>(roleStore);
            
            var model = roleManager.Roles.ToList();
            
            return View(model);
        }

        public ActionResult RolEkle()
        {

            return View("");
        }
        [HttpPost]
        public ActionResult RolEkle(RolEkleModel rol)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            if (roleManager.RoleExists(rol.RolAd) == false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));
            }
           
            return RedirectToAction("Index");
        }

        public ActionResult RolKullaniciEkle()
        {
            

            return View();
        }
        [HttpPost]
        public ActionResult RolKullaniciEkle(RolKullaniciEkleModel model)
        {
            
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var kullanici = userManager.FindByName(model.KullaniciAdi);
            

            if (!userManager.IsInRole(kullanici.Id,model.RolAdi))
            {
                userManager.AddToRole(kullanici.Id, model.RolAdi);
            }
          
            return RedirectToAction("Index");
        }










    }
}

MvcWeb2/MvcWeb2/Areas/Admin/Views/RolYonetim/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="container">
    <div class="col-md-6">

        <div id="1">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#4f8edc">
                    <h4>Roller ve Sayıları</h4>
                </div>
                <div class="panel-body">
                    <ul>
                        @foreach (var item in Model)
                        {

                            <li>@item.Name - @item.Users.Count </li>

                        }
                    </ul>
                    <br />
                    @Html.ActionLink("Yeni Rol Ekle","RolEkle")
                </div>
            </div>
        </div>
    </div>
</div>

MvcWeb2/MvcWeb2/Areas/Admin/Views/RolYonetim/RolEkle.cshtml
@model MvcWeb2.Areas.Admin.Models.RolEkleModel
@{
    ViewBag.Title = "RolEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}




<div class="container">
    <div class="col-md-6">

        <div id="1">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#4f8edc">
                    <h4>RolEkle</h4>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("RolEkle", "RolYonetim", FormMethod.Post))
                    {
                        @Html.TextBoxFor(m => m.RolAd);
                        <input type="submit" />

                    }
                </div>
            </div>
        </div>
    </div>
</div>

MvcWeb2/MvcWeb2/Areas/Admin/Views/RolYonetim/RolKullaniciEkle.cshtml
@model MvcWeb2.Areas.Admin.Models.RolKullaniciEkleModel
@{
    ViewBag.Title = "RolKullaniciEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}




<div class="container">
    <div class="col-md-6">

        <div id="1">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#4f8edc">
                    <h4>RolKullaniciEkle</h4>
                </div>
                <div class="panel-body">
                   @using (Html.BeginForm("RolKullaniciEkle", "RolYonetim", FormMethod.Post))
                   {
                    <h3> @Html.LabelFor(m => m.KullaniciAdi)</h3>@Html.TextAreaFor(m => m.KullaniciAdi)

                    <br/>
                    <h3> @Html.LabelFor(m => m.RolAdi)</h3>@Html.TextAreaFor(m => m.RolAdi)
                    <br />
                    <input type="submit" />
                   }
                </div>
            </div>
        </div>
    </div>
</div>